parameters:
  app.cover_dir: "%kernel.project_dir%/public/cover"
  app.config_dir: "%kernel.project_dir%/var/"
  redisearch.url: "%env(resolve:REDISEARCH_URL)%"
  completions.type: ['storage', 'authors', 'owner']