easy_admin:
    site_name: 'Livres <small>&mdash; Keep track of your books</small>'
    user:
      display_avatar: false
    entities:
        - App\Entity\Book
        - App\Entity\Movement
        - class: App\Entity\ProviderConfiguration
          name: ProviderConfiguration
          form:
              fields:
                  - provider
                  - active
                  - {property: "parameters", type_options: { block_name: 'parameters', allow_add: false, delete_empty: false }}
        - class: App\Entity\User
          name: User
          form:
            fields:
              - username
              - password
              - property: "roles"
                type: choice
                type_options:
                  mapped: true
                  expanded: true
                  multiple: true
                  choices: !php/const App\Entity\User::ROLES

    design:
        menu:
          - { entity: 'Book', label: "Books", icon: 'book' }
          - { entity: 'Movement', label: "Movements", icon: 'people-arrows' }
          - { label: "Configurations" }
          - { entity: 'ProviderConfiguration', label: "Providers Configuration", icon: 'sliders-h' }
          - { label: "Display Configurations", icon: 'desktop', route: admin_display_settings }
          - { label: "Others" }
          - { label: "Search Engine", route: admin_search_engine, icon: 'search' }
          - { label: "Covers", route: admin_image, icon: 'image' }
          - { entity: "User", label: "Users", icon: 'user-cog' }
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - 'admin/form.html.twig'