# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        book_cover:
        book_fragment:
            quality: 80
        book_preview:
            quality: 70
            filters:
                thumbnail:
                    size: [300, 400]
                    mode: outbound
                    allow_upscale: true

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "images/cache"

    loaders:
        default:
            filesystem:
                data_root:
                    - "%app.cover_dir%"
                    - "%kernel.project_dir%/public/"
