version: '3'
services:
  webserver:
    image: nginx:1.17-alpine
    volumes:
      - .:/srv/app:ro
      - ./.docker/nginx.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`livres.docker`)"
      - "traefik.http.routers.php.entrypoints=secure"
      - "traefik.http.routers.php.tls=true"

      - "traefik.http.routers.unsecure-php.rule=Host(`livres.docker`)"
      - "traefik.http.routers.unsecure-php.entrypoints=web"
      - "traefik.http.routers.unsecure-php.middlewares=force-https"
      - "traefik.http.routers.unsecure-php.tls=false"

      - "traefik.http.middlewares.force-https.redirectscheme.scheme=https"

  php:
    build:
      context: ./.docker
      dockerfile: php.Dockerfile
    ports:
      - 9000
    volumes:
      - .:/srv/app:delegated
    working_dir: /srv/app
    labels:
      - "traefik.enable=false"

  redisearch:
    image: "redislabs/redisearch:2.0.5"
    ports:
      - 6379
    labels:
      - "traefik.enable=false"