version: 2
jobs:
  analyze-php:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Install PHP Extension
          command: |
            sudo docker-php-ext-install zip bcmath intl xsl gd
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-

      - run:
          name: Run code quality analysis
          command: NO_DOCKER=1 make analyze-php

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
  analyze-js-css:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run:
          name: Run code quality analysis
          command: NO_DOCKER=1 make analyze-svelte analyze-css
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  commit-workflow:
    jobs:
      - analyze-php
      - analyze-js-css